version: "3.1"

services:
  nginx:
    build: docker/nginx
    container_name: "docker-laravel_nginx"
    ports:
      - "8000:80"
    depends_on:
      - php-fpm
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/

  php-fpm:
    build: docker/php
    container_name: "docker-laravel_php"
    volumes:
      - ./src:/var/www
    environment:
      - DB_HOST="${DB_HOST}"
      - DB_DATABASE="${DB_DATABASE}"
      - DB_USERNAME="${DB_USERNAME}"
      - DB_PASSWORD="${DB_PASSWORD}"
