version: "3.1"

services:
  nginx:
    build: docker/nginx
    container_name: "docker-laravel_nginx"
    depends_on:
      - php-fpm
      - db
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    ports:
      - "8000:80"
    restart: always

  php-fpm:
    build: docker/php
    container_name: "docker-laravel_php"
    depends_on:
      - db
    volumes:
      - ./src:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - DB_HOST="${DB_HOST}"
      - DB_DATABASE="${DB_DATABASE}"
      - DB_USERNAME="${DB_USERNAME}"
      - DB_PASSWORD="${DB_PASSWORD}"
    restart: always

  db:
    build: docker/mysql
    container_name: "docker-laravel_db"
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
      - MYSQL_DATABASE="${DB_DATABASE}"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

volumes:
  db-store:
